<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>localizestay-booking-dev</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" />
    <PackageReference Include="Rmq.CloudEvents" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../2-Application/LocalizeStay.Booking.Application/LocalizeStay.Booking.Application.csproj" />
    <ProjectReference Include="../../4-Infra/LocalizeStay.Booking.Infra/LocalizeStay.Booking.Infra.csproj" />
  </ItemGroup>

</Project>
