<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/2-Application/LocalizeStay.Booking.Application/LocalizeStay.Booking.Application.csproj" />
    <ProjectReference Include="../../src/3-Domain/LocalizeStay.Booking.Domain/LocalizeStay.Booking.Domain.csproj" />
    <ProjectReference Include="../../src/4-Infra/LocalizeStay.Booking.Infra/LocalizeStay.Booking.Infra.csproj" />
  </ItemGroup>

</Project>
